[2020-02-05 03:44:09,679: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-05 03:44:09,705: INFO/MainProcess] mingle: searching for neighbors
[2020-02-05 03:44:10,759: INFO/MainProcess] mingle: all alone
[2020-02-05 03:44:10,788: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-05 03:44:10,789: INFO/MainProcess] celery@b81be8188c0b ready.
[2020-02-05 09:55:29,376: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-05 09:55:29,416: INFO/MainProcess] mingle: searching for neighbors
[2020-02-05 09:55:30,445: INFO/MainProcess] mingle: all alone
[2020-02-05 09:55:30,474: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-05 09:55:30,476: INFO/MainProcess] celery@132a1ba6b399 ready.
[2020-02-05 10:36:48,160: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-05 10:36:48,175: INFO/MainProcess] mingle: searching for neighbors
[2020-02-05 10:36:49,207: INFO/MainProcess] mingle: all alone
[2020-02-05 10:36:49,274: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-05 10:36:49,278: INFO/MainProcess] celery@132a1ba6b399 ready.
[2020-02-05 10:43:07,651: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 185, in _read_from_socket
    raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
OSError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.6/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/usr/local/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.6/site-packages/kombu/transport/redis.py", line 1052, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.6/site-packages/kombu/transport/redis.py", line 348, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.6/site-packages/kombu/transport/redis.py", line 679, in _receive
    ret.append(self._receive_one(c))
  File "/usr/local/lib/python3.6/site-packages/kombu/transport/redis.py", line 690, in _receive_one
    response = c.parse_response()
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 3036, in parse_response
    return self._execute(connection, connection.read_response)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 3013, in _execute
    return command(*args)
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 637, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 290, in read_response
    response = self._buffer.readline()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 224, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 199, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)
[2020-02-05 10:43:07,696: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error 111 connecting to redis:6379. Connection refused..
Trying again in 2.00 seconds...

[2020-02-05 10:47:43,104: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-05 10:47:43,122: INFO/MainProcess] mingle: searching for neighbors
[2020-02-05 10:47:44,116: INFO/MainProcess] mingle: all alone
[2020-02-05 10:47:44,142: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-05 10:47:44,144: INFO/MainProcess] celery@132a1ba6b399 ready.
[2020-02-06 02:20:39,154: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-06 02:20:39,185: INFO/MainProcess] mingle: searching for neighbors
[2020-02-06 02:20:40,230: INFO/MainProcess] mingle: all alone
[2020-02-06 02:20:40,268: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-06 02:20:40,268: INFO/MainProcess] celery@deadb7f88c7c ready.
[2020-02-06 02:23:05,243: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-06 02:23:05,262: INFO/MainProcess] mingle: searching for neighbors
[2020-02-06 02:23:06,299: INFO/MainProcess] mingle: all alone
[2020-02-06 02:23:06,310: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-06 02:23:06,310: INFO/MainProcess] celery@fc18ec39c0e5 ready.
<<<<<<< HEAD
[2020-02-07 04:10:39,897: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-07 04:10:39,930: INFO/MainProcess] mingle: searching for neighbors
[2020-02-07 04:10:40,992: INFO/MainProcess] mingle: all alone
[2020-02-07 04:10:41,008: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-07 04:10:41,009: INFO/MainProcess] celery@6c3ab63219e8 ready.
[2020-02-08 09:33:11,653: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-08 09:33:11,679: INFO/MainProcess] mingle: searching for neighbors
[2020-02-08 09:33:12,768: INFO/MainProcess] mingle: all alone
[2020-02-08 09:33:12,864: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-08 09:33:12,866: INFO/MainProcess] celery@ed11dbb0de3e ready.
[2020-02-10 02:55:34,225: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-10 02:55:34,243: INFO/MainProcess] mingle: searching for neighbors
[2020-02-10 02:55:35,266: INFO/MainProcess] mingle: all alone
[2020-02-10 02:55:35,279: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-10 02:55:35,280: INFO/MainProcess] celery@57e886bd1d7a ready.
[2020-02-12 11:44:41,045: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-12 11:44:41,062: INFO/MainProcess] mingle: searching for neighbors
[2020-02-12 11:44:42,097: INFO/MainProcess] mingle: all alone
[2020-02-12 11:44:42,118: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-12 11:44:42,121: INFO/MainProcess] celery@54e777a083db ready.
[2020-02-16 02:09:53,225: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-16 02:09:53,245: INFO/MainProcess] mingle: searching for neighbors
[2020-02-16 02:09:54,276: INFO/MainProcess] mingle: all alone
[2020-02-16 02:09:54,293: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-16 02:09:54,295: INFO/MainProcess] celery@7fa1878a854e ready.
[2020-02-17 06:07:23,786: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-17 06:07:23,807: INFO/MainProcess] mingle: searching for neighbors
[2020-02-17 06:07:24,836: INFO/MainProcess] mingle: all alone
[2020-02-17 06:07:24,861: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-17 06:07:24,862: INFO/MainProcess] celery@49223bb35dae ready.
=======
[2020-02-16 02:14:07,151: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-16 02:14:07,162: INFO/MainProcess] mingle: searching for neighbors
[2020-02-16 02:14:08,180: INFO/MainProcess] mingle: all alone
[2020-02-16 02:14:08,193: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-16 02:14:08,193: INFO/MainProcess] celery@9aeabb71b439 ready.
[2020-02-17 01:59:25,865: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-17 01:59:25,889: INFO/MainProcess] mingle: searching for neighbors
[2020-02-17 01:59:26,906: INFO/MainProcess] mingle: all alone
[2020-02-17 01:59:26,978: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-17 01:59:26,979: INFO/MainProcess] celery@9aeabb71b439 ready.
<<<<<<< HEAD
>>>>>>> 15a4c6ac0bcd4f9acce4fd5aadf10ecede314d80
[2020-02-17 06:09:44,825: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-17 06:09:44,838: INFO/MainProcess] mingle: searching for neighbors
[2020-02-17 06:09:45,882: INFO/MainProcess] mingle: all alone
[2020-02-17 06:09:45,898: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-17 06:09:45,898: INFO/MainProcess] celery@ec5ded36e4ef ready.
[2020-02-17 08:33:40,431: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-17 08:33:40,443: INFO/MainProcess] mingle: searching for neighbors
[2020-02-17 08:33:41,473: INFO/MainProcess] mingle: all alone
[2020-02-17 08:33:41,494: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-17 08:33:41,500: INFO/MainProcess] celery@890f42962023 ready.
[2020-02-18 02:58:05,365: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-18 02:58:05,394: INFO/MainProcess] mingle: searching for neighbors
[2020-02-18 02:58:06,422: INFO/MainProcess] mingle: all alone
[2020-02-18 02:58:06,442: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-18 02:58:06,443: INFO/MainProcess] celery@fd4fb6141029 ready.
=======
[2020-02-17 08:14:15,413: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-17 08:14:15,424: INFO/MainProcess] mingle: searching for neighbors
[2020-02-17 08:14:16,440: INFO/MainProcess] mingle: all alone
[2020-02-17 08:14:16,452: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-17 08:14:16,452: INFO/MainProcess] celery@9aeabb71b439 ready.
[2020-02-18 02:59:22,701: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-18 02:59:22,786: INFO/MainProcess] mingle: searching for neighbors
[2020-02-18 02:59:23,813: INFO/MainProcess] mingle: all alone
[2020-02-18 02:59:23,959: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-18 02:59:23,959: INFO/MainProcess] celery@9aeabb71b439 ready.
[2020-02-18 03:06:39,729: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-18 03:06:39,738: INFO/MainProcess] mingle: searching for neighbors
[2020-02-18 03:06:40,757: INFO/MainProcess] mingle: all alone
[2020-02-18 03:06:40,772: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-18 03:06:40,774: INFO/MainProcess] celery@9aeabb71b439 ready.
<<<<<<< HEAD
>>>>>>> 78f8520c1fc78ff5243020c418ba84886835616c
[2020-02-18 03:54:59,883: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-18 03:54:59,902: INFO/MainProcess] mingle: searching for neighbors
[2020-02-18 03:55:00,940: INFO/MainProcess] mingle: all alone
[2020-02-18 03:55:00,955: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-18 03:55:00,956: INFO/MainProcess] celery@26ef31fc378b ready.
=======
[2020-02-18 03:36:59,572: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-18 03:36:59,586: INFO/MainProcess] mingle: searching for neighbors
[2020-02-18 03:37:00,602: INFO/MainProcess] mingle: all alone
[2020-02-18 03:37:00,610: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-18 03:37:00,610: INFO/MainProcess] celery@9aeabb71b439 ready.
[2020-02-18 03:56:51,452: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-18 03:56:51,460: INFO/MainProcess] mingle: searching for neighbors
[2020-02-18 03:56:52,478: INFO/MainProcess] mingle: all alone
[2020-02-18 03:56:52,485: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-18 03:56:52,485: INFO/MainProcess] celery@9aeabb71b439 ready.
[2020-02-18 04:33:58,924: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-18 04:33:58,943: INFO/MainProcess] mingle: searching for neighbors
[2020-02-18 04:33:59,981: INFO/MainProcess] mingle: all alone
[2020-02-18 04:33:59,989: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-18 04:33:59,989: INFO/MainProcess] celery@9aeabb71b439 ready.
[2020-02-18 06:44:37,856: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-18 06:44:37,864: INFO/MainProcess] mingle: searching for neighbors
[2020-02-18 06:44:38,878: INFO/MainProcess] mingle: all alone
[2020-02-18 06:44:38,885: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-18 06:44:38,886: INFO/MainProcess] celery@9aeabb71b439 ready.
[2020-02-18 07:09:17,972: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-18 07:09:17,979: INFO/MainProcess] mingle: searching for neighbors
[2020-02-18 07:09:18,995: INFO/MainProcess] mingle: all alone
[2020-02-18 07:09:19,002: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-18 07:09:19,003: INFO/MainProcess] celery@e33f53eb411c ready.
<<<<<<< HEAD
>>>>>>> 2e8ab51ae1831be6a5e2ce66ce8c21ecff33cc8f
[2020-02-18 07:15:40,045: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-18 07:15:40,063: INFO/MainProcess] mingle: searching for neighbors
[2020-02-18 07:15:41,098: INFO/MainProcess] mingle: all alone
[2020-02-18 07:15:41,121: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-18 07:15:41,123: INFO/MainProcess] celery@67c5cb698b40 ready.
[2020-02-18 08:32:15,542: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-18 08:32:15,562: INFO/MainProcess] mingle: searching for neighbors
[2020-02-18 08:32:16,588: INFO/MainProcess] mingle: all alone
[2020-02-18 08:32:16,608: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-18 08:32:16,609: INFO/MainProcess] celery@7865322db207 ready.
[2020-02-18 09:23:15,658: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-18 09:23:15,688: INFO/MainProcess] mingle: searching for neighbors
[2020-02-18 09:23:16,713: INFO/MainProcess] mingle: all alone
[2020-02-18 09:23:16,737: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-18 09:23:16,738: INFO/MainProcess] celery@7865322db207 ready.
=======
[2020-02-18 07:17:00,918: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-18 07:17:00,927: INFO/MainProcess] mingle: searching for neighbors
[2020-02-18 07:17:01,949: INFO/MainProcess] mingle: all alone
[2020-02-18 07:17:01,966: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-18 07:17:01,967: INFO/MainProcess] celery@e33f53eb411c ready.
[2020-02-18 08:01:09,454: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-18 08:01:09,465: INFO/MainProcess] mingle: searching for neighbors
[2020-02-18 08:01:10,484: INFO/MainProcess] mingle: all alone
[2020-02-18 08:01:10,497: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-18 08:01:10,497: INFO/MainProcess] celery@8d5f6b6f108e ready.
[2020-02-18 08:49:12,960: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-18 08:49:12,967: INFO/MainProcess] mingle: searching for neighbors
[2020-02-18 08:49:13,983: INFO/MainProcess] mingle: all alone
[2020-02-18 08:49:13,990: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-18 08:49:13,990: INFO/MainProcess] celery@8d5f6b6f108e ready.
<<<<<<< HEAD
>>>>>>> d8bca1bf1b1e27e77e4e16479c84432bf5f92f03
[2020-02-19 01:47:10,439: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-19 01:47:10,463: INFO/MainProcess] mingle: searching for neighbors
[2020-02-19 01:47:11,523: INFO/MainProcess] mingle: all alone
[2020-02-19 01:47:11,541: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-19 01:47:11,543: INFO/MainProcess] celery@7865322db207 ready.
[2020-02-20 02:50:41,723: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-20 02:50:41,751: INFO/MainProcess] mingle: searching for neighbors
[2020-02-20 02:50:42,794: INFO/MainProcess] mingle: all alone
[2020-02-20 02:50:42,812: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-20 02:50:42,814: INFO/MainProcess] celery@5099b6049917 ready.
[2020-02-20 10:22:26,822: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-20 10:22:26,836: INFO/MainProcess] mingle: searching for neighbors
[2020-02-20 10:22:27,865: INFO/MainProcess] mingle: all alone
[2020-02-20 10:22:27,887: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-20 10:22:27,888: INFO/MainProcess] celery@844b070d6f41 ready.
=======
[2020-02-25 07:40:28,452: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-25 07:40:28,542: INFO/MainProcess] mingle: searching for neighbors
[2020-02-25 07:40:29,577: INFO/MainProcess] mingle: all alone
[2020-02-25 07:40:29,625: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-25 07:40:29,625: INFO/MainProcess] celery@84fd04c3e51c ready.
[2020-02-25 10:20:12,964: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-25 10:20:13,026: INFO/MainProcess] mingle: searching for neighbors
[2020-02-25 10:20:14,123: INFO/MainProcess] mingle: all alone
[2020-02-25 10:20:14,680: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-25 10:20:14,681: INFO/MainProcess] celery@84fd04c3e51c ready.
>>>>>>> 9b0bd83a4a7b04e251c2991dcb4e2ef4d8d3dd7a
[2020-02-28 00:29:18,147: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-28 00:29:18,172: INFO/MainProcess] mingle: searching for neighbors
[2020-02-28 00:29:19,199: INFO/MainProcess] mingle: all alone
[2020-02-28 00:29:19,235: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-28 00:29:19,237: INFO/MainProcess] celery@844b070d6f41 ready.
<<<<<<< HEAD
[2020-02-28 10:15:17,674: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-28 10:15:17,691: INFO/MainProcess] mingle: searching for neighbors
[2020-02-28 10:15:18,724: INFO/MainProcess] mingle: all alone
[2020-02-28 10:15:18,736: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-28 10:15:18,736: INFO/MainProcess] celery@290d4b18e52a ready.
[2020-02-28 11:03:58,874: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-28 11:03:58,893: INFO/MainProcess] mingle: searching for neighbors
[2020-02-28 11:03:59,999: INFO/MainProcess] mingle: all alone
[2020-02-28 11:04:00,027: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-28 11:04:00,027: INFO/MainProcess] celery@290d4b18e52a ready.
[2020-03-02 02:23:41,451: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-03-02 02:23:41,506: INFO/MainProcess] mingle: searching for neighbors
[2020-03-02 02:23:42,552: INFO/MainProcess] mingle: all alone
[2020-03-02 02:23:42,566: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-03-02 02:23:42,566: INFO/MainProcess] celery@290d4b18e52a ready.
=======
[2020-02-28 09:41:40,972: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-28 09:41:41,052: INFO/MainProcess] mingle: searching for neighbors
[2020-02-28 09:41:42,093: INFO/MainProcess] mingle: all alone
[2020-02-28 09:41:42,135: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-28 09:41:42,136: INFO/MainProcess] celery@f194d10df534 ready.
[2020-02-28 10:55:30,774: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-28 10:55:30,814: INFO/MainProcess] mingle: searching for neighbors
[2020-02-28 10:55:31,844: INFO/MainProcess] mingle: all alone
[2020-02-28 10:55:31,879: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-28 10:55:31,879: INFO/MainProcess] celery@f194d10df534 ready.
[2020-02-28 11:03:54,944: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-28 11:03:55,287: INFO/MainProcess] mingle: searching for neighbors
[2020-02-28 11:03:56,392: INFO/MainProcess] mingle: all alone
[2020-02-28 11:03:56,489: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-28 11:03:56,490: INFO/MainProcess] celery@f194d10df534 ready.
[2020-02-28 11:40:02,754: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-28 11:40:02,974: INFO/MainProcess] mingle: searching for neighbors
[2020-02-28 11:40:04,076: INFO/MainProcess] mingle: all alone
[2020-02-28 11:40:04,177: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-28 11:40:04,177: INFO/MainProcess] celery@f194d10df534 ready.
[2020-02-28 11:44:40,558: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-28 11:44:40,630: INFO/MainProcess] mingle: searching for neighbors
[2020-02-28 11:44:41,661: INFO/MainProcess] mingle: all alone
[2020-02-28 11:44:41,679: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-28 11:44:41,679: INFO/MainProcess] celery@f194d10df534 ready.
[2020-02-29 02:50:17,003: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-29 02:50:17,095: INFO/MainProcess] mingle: searching for neighbors
[2020-02-29 02:50:18,126: INFO/MainProcess] mingle: all alone
[2020-02-29 02:50:18,326: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-29 02:50:18,327: INFO/MainProcess] celery@f194d10df534 ready.
<<<<<<< HEAD
[2020-02-29 08:47:10,796: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-29 08:47:10,854: INFO/MainProcess] mingle: searching for neighbors
[2020-02-29 08:47:11,901: INFO/MainProcess] mingle: all alone
[2020-02-29 08:47:11,934: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-29 08:47:11,934: INFO/MainProcess] celery@2ed5c1e51ba8 ready.
[2020-02-29 08:50:57,851: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-29 08:50:57,959: INFO/MainProcess] mingle: searching for neighbors
[2020-02-29 08:50:59,125: INFO/MainProcess] mingle: all alone
[2020-02-29 08:50:59,154: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-29 08:50:59,154: INFO/MainProcess] celery@2ed5c1e51ba8 ready.
[2020-02-29 09:13:19,651: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-29 09:13:19,671: INFO/MainProcess] mingle: searching for neighbors
[2020-02-29 09:13:20,709: INFO/MainProcess] mingle: all alone
[2020-02-29 09:13:20,728: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-29 09:13:20,728: INFO/MainProcess] celery@2ed5c1e51ba8 ready.
[2020-02-29 09:19:59,471: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-02-29 09:19:59,598: INFO/MainProcess] mingle: searching for neighbors
[2020-02-29 09:20:00,631: INFO/MainProcess] mingle: all alone
[2020-02-29 09:20:00,672: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-02-29 09:20:00,672: INFO/MainProcess] celery@2ed5c1e51ba8 ready.
[2020-03-02 03:52:22,282: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-03-02 03:52:22,470: INFO/MainProcess] mingle: searching for neighbors
[2020-03-02 03:52:23,501: INFO/MainProcess] mingle: all alone
[2020-03-02 03:52:23,548: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-03-02 03:52:23,548: INFO/MainProcess] celery@2ed5c1e51ba8 ready.
[2020-03-02 04:18:33,916: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-03-02 04:18:34,123: INFO/MainProcess] mingle: searching for neighbors
[2020-03-02 04:18:35,211: INFO/MainProcess] mingle: all alone
[2020-03-02 04:18:35,520: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-03-02 04:18:35,520: INFO/MainProcess] celery@2ed5c1e51ba8 ready.
[2020-03-02 04:36:58,190: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-03-02 04:36:58,635: INFO/MainProcess] mingle: searching for neighbors
[2020-03-02 04:36:59,731: INFO/MainProcess] mingle: all alone
[2020-03-02 04:36:59,814: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-03-02 04:36:59,819: INFO/MainProcess] celery@2ed5c1e51ba8 ready.
[2020-03-02 04:43:29,468: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-03-02 04:43:29,655: INFO/MainProcess] mingle: searching for neighbors
[2020-03-02 04:43:30,774: INFO/MainProcess] mingle: all alone
[2020-03-02 04:43:30,812: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-03-02 04:43:30,813: INFO/MainProcess] celery@2ed5c1e51ba8 ready.
[2020-03-02 05:04:04,609: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-03-02 05:04:04,719: INFO/MainProcess] mingle: searching for neighbors
[2020-03-02 05:04:05,752: INFO/MainProcess] mingle: all alone
[2020-03-02 05:04:05,982: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-03-02 05:04:05,985: INFO/MainProcess] celery@2ed5c1e51ba8 ready.
=======
>>>>>>> 60d88bd4caf37ad386c90c1235ce243455e472ac
[2020-03-02 02:26:48,514: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-03-02 02:26:48,540: INFO/MainProcess] mingle: searching for neighbors
[2020-03-02 02:26:49,601: INFO/MainProcess] mingle: all alone
[2020-03-02 02:26:49,624: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-03-02 02:26:49,624: INFO/MainProcess] celery@290d4b18e52a ready.
[2020-03-02 02:30:46,305: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-03-02 02:30:46,328: INFO/MainProcess] mingle: searching for neighbors
[2020-03-02 02:30:47,367: INFO/MainProcess] mingle: all alone
[2020-03-02 02:30:47,389: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-03-02 02:30:47,389: INFO/MainProcess] celery@290d4b18e52a ready.
[2020-03-02 02:35:50,843: ERROR/MainProcess] Received unregistered task of type 'apps.users.tasks.test_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'apps.users.tasks.test_func'
[2020-03-02 02:37:49,163: ERROR/MainProcess] Received unregistered task of type 'apps.users.tasks.test_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'apps.users.tasks.test_func'
[2020-03-02 02:37:59,319: ERROR/MainProcess] Received unregistered task of type 'apps.users.tasks.test_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'apps.users.tasks.test_func'
[2020-03-02 02:40:05,714: ERROR/MainProcess] Received unregistered task of type 'apps.users.tasks.test_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'apps.users.tasks.test_func'
[2020-03-02 02:42:45,144: ERROR/MainProcess] Received unregistered task of type 'apps.users.tasks.test_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'apps.users.tasks.test_func'
[2020-03-02 02:43:35,830: ERROR/MainProcess] Received unregistered task of type 'apps.users.tasks.test_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'apps.users.tasks.test_func'
[2020-03-02 02:43:48,472: ERROR/MainProcess] Received unregistered task of type 'apps.users.tasks.test_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'apps.users.tasks.test_func'
[2020-03-02 02:47:11,031: ERROR/MainProcess] Received unregistered task of type 'apps.users.tasks.test_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'apps.users.tasks.test_func'
[2020-03-02 02:49:08,651: ERROR/MainProcess] Received unregistered task of type 'apps.users.tasks.test_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'apps.users.tasks.test_func'
[2020-03-02 02:49:48,326: ERROR/MainProcess] Received unregistered task of type 'apps.users.tasks.test_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'apps.users.tasks.test_func'
[2020-03-02 02:50:48,455: ERROR/MainProcess] Received unregistered task of type 'apps.users.tasks.test_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'apps.users.tasks.test_func'
[2020-03-02 02:50:57,872: ERROR/MainProcess] Received unregistered task of type 'apps.users.tasks.test_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'apps.users.tasks.test_func'
[2020-03-02 02:55:15,524: ERROR/MainProcess] Received unregistered task of type 'apps.users.tasks.test_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'apps.users.tasks.test_func'
[2020-03-02 02:55:33,357: ERROR/MainProcess] Received unregistered task of type 'apps.users.tasks.test_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'apps.users.tasks.test_func'
[2020-03-02 02:56:41,434: ERROR/MainProcess] Received unregistered task of type 'apps.users.tasks.test_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'apps.users.tasks.test_func'
[2020-03-02 02:57:15,705: ERROR/MainProcess] Received unregistered task of type 'apps.users.tasks.test_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'apps.users.tasks.test_func'
[2020-03-02 02:58:46,337: ERROR/MainProcess] Received unregistered task of type 'apps.users.tasks.test_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'apps.users.tasks.test_func'
[2020-03-02 02:58:57,809: ERROR/MainProcess] Received unregistered task of type 'apps.users.tasks.test_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'apps.users.tasks.test_func'
[2020-03-02 03:00:19,166: ERROR/MainProcess] Received unregistered task of type 'apps.users.tasks.test_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'apps.users.tasks.test_func'
[2020-03-02 03:06:56,104: ERROR/MainProcess] Received unregistered task of type 'apps.users.tasks.test_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'apps.users.tasks.test_func'
[2020-03-02 03:07:50,971: ERROR/MainProcess] Received unregistered task of type 'apps.users.tasks.test_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'apps.users.tasks.test_func'
[2020-03-02 03:14:21,512: ERROR/MainProcess] Received unregistered task of type 'apps.users.tasks.test_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'apps.users.tasks.test_func'
[2020-03-02 03:24:52,539: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-03-02 03:24:52,566: INFO/MainProcess] mingle: searching for neighbors
[2020-03-02 03:24:53,609: INFO/MainProcess] mingle: all alone
[2020-03-02 03:24:53,658: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-03-02 03:24:53,658: INFO/MainProcess] celery@290d4b18e52a ready.
[2020-03-02 03:25:04,215: INFO/MainProcess] Received task: apps.users.tasks.test_func[28d0fbfc-29b7-4935-9304-a2bfecc8934c]  
[2020-03-02 03:25:04,218: WARNING/ForkPoolWorker-1] resssssssss=
[2020-03-02 03:25:14,266: WARNING/ForkPoolWorker-1] 10 giay sau
[2020-03-02 03:25:15,035: WARNING/ForkPoolWorker-1] 406
[2020-03-02 03:25:15,040: INFO/ForkPoolWorker-1] Task apps.users.tasks.test_func[28d0fbfc-29b7-4935-9304-a2bfecc8934c] succeeded in 10.821695385999647s: None
<<<<<<< HEAD
[2020-03-02 03:27:13,565: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-03-02 03:27:13,585: INFO/MainProcess] mingle: searching for neighbors
[2020-03-02 03:27:14,611: INFO/MainProcess] mingle: all alone
[2020-03-02 03:27:14,623: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-03-02 03:27:14,623: INFO/MainProcess] celery@290d4b18e52a ready.
[2020-03-02 03:27:24,633: INFO/MainProcess] Received task: apps.users.tasks.test_func[4a6ef0f2-ad66-4225-ac37-50b70464e78c]  
[2020-03-02 03:27:24,635: WARNING/ForkPoolWorker-1] resssssssss=
[2020-03-02 03:27:33,577: INFO/MainProcess] Received task: apps.users.tasks.test_func[3ea42a18-58df-4fd1-8c48-4cbed55fda6b]  
[2020-03-02 03:27:33,579: WARNING/ForkPoolWorker-2] resssssssss=
[2020-03-02 03:27:34,641: WARNING/ForkPoolWorker-1] 10 giay sau
[2020-03-02 03:27:35,261: WARNING/ForkPoolWorker-1] 406
[2020-03-02 03:27:35,263: INFO/ForkPoolWorker-1] Task apps.users.tasks.test_func[4a6ef0f2-ad66-4225-ac37-50b70464e78c] succeeded in 10.628296142999716s: None
[2020-03-02 03:27:43,580: WARNING/ForkPoolWorker-2] 10 giay sau
[2020-03-02 03:27:44,193: WARNING/ForkPoolWorker-2] 406
[2020-03-02 03:27:44,196: INFO/ForkPoolWorker-2] Task apps.users.tasks.test_func[3ea42a18-58df-4fd1-8c48-4cbed55fda6b] succeeded in 10.61714498099991s: None
[2020-03-02 03:29:05,786: INFO/MainProcess] Received task: apps.users.tasks.test_func[d0e9f9da-bcbd-4012-bade-8d4e46a389ac]  
[2020-03-02 03:29:05,808: WARNING/ForkPoolWorker-1] resssssssss=
[2020-03-02 03:29:15,817: WARNING/ForkPoolWorker-1] 10 giay sau
[2020-03-02 03:29:16,460: WARNING/ForkPoolWorker-1] 406
[2020-03-02 03:29:16,460: INFO/ForkPoolWorker-1] Task apps.users.tasks.test_func[d0e9f9da-bcbd-4012-bade-8d4e46a389ac] succeeded in 10.65229183700012s: None
[2020-03-02 03:29:38,721: INFO/MainProcess] Received task: apps.users.tasks.test_func[88f625ff-5ff0-4800-b809-12045ba9fa1e]  
[2020-03-02 03:29:38,723: WARNING/ForkPoolWorker-2] resssssssss=
[2020-03-02 03:29:48,730: WARNING/ForkPoolWorker-2] 10 giay sau
[2020-03-02 03:29:49,266: WARNING/ForkPoolWorker-2] 406
[2020-03-02 03:29:49,267: INFO/ForkPoolWorker-2] Task apps.users.tasks.test_func[88f625ff-5ff0-4800-b809-12045ba9fa1e] succeeded in 10.544699035000122s: None
[2020-03-02 03:30:18,486: INFO/MainProcess] Received task: apps.users.tasks.test_func[2350065a-8c36-4fd9-b98e-5c797b659b82]  
[2020-03-02 03:30:18,488: WARNING/ForkPoolWorker-1] resssssssss=
[2020-03-02 03:30:28,497: WARNING/ForkPoolWorker-1] 10 giay sau
[2020-03-02 03:30:29,074: WARNING/ForkPoolWorker-1] 406
[2020-03-02 03:30:29,076: INFO/ForkPoolWorker-1] Task apps.users.tasks.test_func[2350065a-8c36-4fd9-b98e-5c797b659b82] succeeded in 10.588053596999998s: None
[2020-03-02 03:34:01,669: INFO/MainProcess] Received task: apps.users.tasks.test_func[dc9a6d90-0b5c-47f5-9bce-dbceb9e00210]  
[2020-03-02 03:34:01,670: WARNING/ForkPoolWorker-2] resssssssss=
[2020-03-02 03:34:11,681: WARNING/ForkPoolWorker-2] 10 giay sau
[2020-03-02 03:34:12,304: WARNING/ForkPoolWorker-2] 406
[2020-03-02 03:34:12,305: INFO/ForkPoolWorker-2] Task apps.users.tasks.test_func[dc9a6d90-0b5c-47f5-9bce-dbceb9e00210] succeeded in 10.634724556000037s: None
[2020-03-02 03:54:24,418: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-03-02 03:54:24,429: INFO/MainProcess] mingle: searching for neighbors
[2020-03-02 03:54:25,464: INFO/MainProcess] mingle: all alone
[2020-03-02 03:54:25,479: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-03-02 03:54:25,479: INFO/MainProcess] celery@290d4b18e52a ready.
[2020-03-02 08:42:02,135: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-03-02 08:42:02,185: INFO/MainProcess] mingle: searching for neighbors
[2020-03-02 08:42:03,208: INFO/MainProcess] mingle: all alone
[2020-03-02 08:42:03,232: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-03-02 08:42:03,233: INFO/MainProcess] celery@290d4b18e52a ready.
[2020-03-02 10:13:20,022: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-03-02 10:13:20,041: INFO/MainProcess] mingle: searching for neighbors
[2020-03-02 10:13:21,088: INFO/MainProcess] mingle: all alone
[2020-03-02 10:13:21,142: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-03-02 10:13:21,142: INFO/MainProcess] celery@290d4b18e52a ready.
[2020-03-02 10:56:05,283: INFO/MainProcess] Connected to redis://redis:6379/0
[2020-03-02 10:56:05,323: INFO/MainProcess] mingle: searching for neighbors
[2020-03-02 10:56:06,360: INFO/MainProcess] mingle: all alone
[2020-03-02 10:56:06,403: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-03-02 10:56:06,403: INFO/MainProcess] celery@290d4b18e52a ready.
=======
>>>>>>> 3be43c56aa0d71244d51beab13ff44da59252487
>>>>>>> 563c6e4440f8f9cc47c9538a0cb23d88295c0c25
